services:
  backend-database:
    container_name: mobile-app
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - ./docker/volumes/:/var/lib/postgresql/data
    #   - ./docker/postgres-config/postgresql.conf:/etc/postgresql/postgresql.conf
    #   - ./docker/postgres-config/pg_hba.conf:/etc/postgresql/pg_hba.conf
    # command: ['postgres', '-c', 'config_file=/etc/postgresql/postgresql.conf']

volumes:
  postgres:
