services:
  # app:
  #   container_name: api_nestjs
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #     target: development
  #   volumes:
  #     - .:/usr/src/app
  #   env_file:
  #     - .env
  #   command: pnpm start:dev
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - db

  backend-database:
    container_name: mobile-app
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - ./docker/volumes/:/var/lib/postgresql/data

volumes:
  postgres:
